"""Add segment and segment effort fields

Revision ID: 28d5a89e12fc
Revises: a8e8ddd4d838
Create Date: 2025-03-02 13:37:22.487539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d5a89e12fc'
down_revision = 'a8e8ddd4d838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_efforts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moving_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_watts', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_heartrate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_heartrate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('kom_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pr_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('start_latlng', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('end_latlng', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('climb_category', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('private', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hazardous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('hazardous')
        batch_op.drop_column('private')
        batch_op.drop_column('country')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('climb_category')
        batch_op.drop_column('end_latlng')
        batch_op.drop_column('start_latlng')
        batch_op.drop_column('activity_type')

    with op.batch_alter_table('segment_efforts', schema=None) as batch_op:
        batch_op.drop_column('pr_rank')
        batch_op.drop_column('kom_rank')
        batch_op.drop_column('max_heartrate')
        batch_op.drop_column('average_heartrate')
        batch_op.drop_column('average_watts')
        batch_op.drop_column('distance')
        batch_op.drop_column('moving_time')

    # ### end Alembic commands ###
